# Generated by Django 4.1 on 2022-08-20 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_At')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Is_Deleted')),
                ('type', models.CharField(choices=[('normal_shipping', 'Normal'), ('express_shipping', 'Express')], max_length=30, verbose_name='type')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiptobasket', to='orders.basket', verbose_name='basket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
