# Generated by Django 4.1 on 2022-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is_done'),
        ),
    ]
